### ISSUE TITLE
Archive iOS project fails

### ISSUE THREAD

**Issue by dcacenabes** [andreacremaschi/SpatialDBKit#15]
The app builds and runs fine on simulator or device, but when I try to archive the app I get:
`Implicit declaration of function 'virtualshape_extension_init' is invalid in C99` in the Pods-spatialite project.
And the same goes for
virtualdbf_extension_init
virtualtext_extension_init
virtualnetwork_extension_init
mbrcache_extension_init
virtualfdo_extension_init
virtual_spatialindex_extension_init

Thus I cannot generate an ipa to distribute.

**Comment by burhanuddin353** [comment]
When I replace the row 87 in spatialite.c:

```
#include <spatialite/spatialite.h>
```

with:

```
#include <spatialite/spatialite/spatialite.h>
```

it throws this 
**'spatialite/spatialite.h' file not found.**

**Comment by burhanuddin353** [comment]
cocoapods issue it was.

https://github.com/andreacremaschi/SpatialDBKit/issues/26
