### ISSUE TITLE
Support for 64 bits?

### ISSUE THREAD

**Issue by doubotis** [andreacremaschi/SpatialDBKit#20]
Hi!

Firstly thanks for your work. I turn your project into a .framework package and it works very well as module on many apps of my company.

Perhaps do you have read/listen to Apple will force developpers to switch to 64bits in 2015. Is this library already ready for 64bits or this must be updated?

**Comment by doubotis** [comment]
Update about this issue: Working on it tomorrow. I'll tell if something goes wrong.

**Comment by andreacremaschi** [comment]
Great!

**Comment by doubotis** [comment]
Works like a charm! Simply update the "Valid Architectures" to get support for arm64 architecture and let's rock.
