### ISSUE TITLE
How to use "RTreeIntersects"?

### ISSUE THREAD

**Issue by DennisZP** [andreacremaschi/SpatialDBKit#23]
When I perform
"SpatialDatabase *db = [SpatialDatabase databaseWithPath: dbPath];
    [db open];
    
    NSString *str = [NSString stringWithFormat:@"select segment_id, Geometry from segment where Rowid in( SELECT rowid FROM idx_segment_geometry WHERE pkid MATCH RTreeIntersects(100,30,110,60));"];
    FMResultSet *rs = [db executeQuery:str];
    while ([rs next]) {
        NSLog(@"%@", [rs resultDictionary]);
    
    }"
Execution result is this:
Spatialite initialization
SpatiaLite version ..: 4.1.1	Supported Extensions:
	- 'VirtualShape'	[direct Shapefile access]
	- 'VirtualDbf'		[direct DBF access]
	- 'VirtualText'		[direct CSV/TXT access]
	- 'VirtualNetwork'	[Dijkstra shortest path]
	- 'RTree'		[Spatial Index - R*Tree]
	- 'MbrCache'		[Spatial Index - MBR cache]
	- 'VirtualSpatialIndex'	[R*Tree metahandler]
	- 'VirtualFDO'		[FDO-OGR interoperability]
	- 'SpatiaLite'		[Spatial SQL - OGC]
PROJ.4 version ......: Rel. 4.8.0, 6 March 2012
GEOS version ........: 3.4.2-CAPI-1.8.2 r0
2015-04-20 14:23:53.726 WhirlyDemo2[19713:60b] DB Error: 1 "no such function: RTreeIntersects"
2015-04-20 14:23:53.727 WhirlyDemo2[19713:60b] DB Query: select segment_id, Geometry from segment where Rowid in( SELECT rowid FROM idx_segment_geometry WHERE pkid MATCH RTreeIntersects(100,30,110,60));
2015-04-20 14:23:53.729 WhirlyDemo2[19713:60b] DB Path: /var/mobile/Applications/6373A75F-328E-4FD0-9E0C-F7521887921A/Documents/db.sqlite

Why Rtree been introduced,Or error"no such function: RTreeIntersects"

**Comment by doubotis** [comment]
It seems you enable correctly the RTree module.
Please try the function `ST_RTreeIntersects`, like :
```
NSString *str = [NSString stringWithFormat:@"select segment_id, Geometry from segment where Rowid in( SELECT rowid FROM idx_segment_geometry WHERE pkid MATCH ST_RTreeIntersects(100,30,110,60));"];
```

The reason to do this is because on Spatialite 4.0+ updates the `RTReeIntersects` function is deprecated. Due to new spatial database conventions all spatial functions must be prefixed by `ST_`

If you cannot use the new functions, you can enable the old functions (strongly discouraged) by setting a C flag option `--enable-geocallbacks=yes` into the spatialite project.

**Comment by andreacremaschi** [comment]
Ok! I read this now, but actually I never used that function so I wouldn't be of help. Thank you, I'll close this.
