### ISSUE TITLE
Issues while integrating HERE Premium SDK 

### ISSUE THREAD

**Issue by burhanuddin353** [andreacremaschi/SpatialDBKit#27]
The application crashes on `db.open()` command. It crashes on `sqlite3.c` file at `mallocWithAlarm` at line `sqlite3GlobalConfig.m.xRoundup(n)`.

Could you help me with this? I would appreciate if you could give me your contact details if possible so it would be easy to discuss with the issues which I am facing and you can guide me through it atleast if not fix.

Thanks.

**Comment by andreacremaschi** [comment]
Sorry no, it's not happening. As I said [before](https://github.com/andreacremaschi/SpatialDBKit/issues/22#issuecomment-244061288) I am not developing the project anymore. Good luck with it and feel free to share your progress if you think it's worth it.
