### ISSUE TITLE
Error during 'pod install', installing geos (3.4.2), alias commands wrong?

### ISSUE THREAD

**Issue by scspijker** [andreacremaschi/SpatialDBKit#9]
During a

```
pod install
```

I get the following error(s)

```
MacMini:iOS Project username$ pod install
Analyzing dependencies
Downloading dependencies
Installing FMDB (2.2)
Installing ShapeKit (0.9.3)
Installing SpatialDBKit (0.1.1)
Installing geos (3.4.2)
[!] Pod::Executable
set -e

type -P autoconf &>/dev/null || alias autoconf 'xcrun autoconf'
type -P autoheader &>/dev/null || alias autoheader 'xcrun autoheader'
type -P aclocal &>/dev/null || alias aclocal 'xcrun aclocal'
type -P automake &>/dev/null || alias automake 'xcrun automake'
type -P glibtool &>/dev/null || alias glibtool 'xcrun glibtool'
type -P glibtoolize &>/dev/null || alias glibtoolize 'xcrun glibtoolize'

sh autogen.sh
./configure
./tools/svn_repo_revision.sh

cat <<EOT >> include/geos/platform.h
    #undef ISNAN
    #define ISNAN(x) (std::isnan(x))
EOT


sh: line 3: alias: autoconf: not found

sh: line 3: alias: xcrun autoconf: not found
```

I see the code says 

```
alias autoconf 'xcrun autoconf'
```

Shouldn't this be

```
alias autoconf='xcrun autoconf'
```

Still, running 'xcrun autoconf' gives me an error

```
MacMini:iOS Project username$ xcrun autoconf
xcrun: error: unable to find utility "autoconf", not a developer tool or in PATH
```

XCode 5.0.2, with commandline tools installed
Mac OS 10.8.5
Ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]
Gem 2.2.2

**Comment by jaakla** [comment]
After installing libtool from source I also had to do following hack to get it to run, otherwise pod install was complaining about missing glibtool* . 

    sudo ln /usr/local/bin/libtoolize /usr/local/bin/glibtoolize
    sudo ln /usr/local/bin/libtool /usr/local/bin/glibtool

It seems that something in the toolchain requires glibtool* , maybe geos. Can you fix it in podspec level?

**Comment by andreacremaschi** [comment]
There is a note in the README already: 

```
brew install automake autoconf libtool
```

**Comment by jaakla** [comment]
Does brew really install also glibtool and glibtoolize this way? I don't use brew/port anymore, as they tend to mess up system/libs in long run, just make from source is safer. So I cant try. I suspect I (and you) had the glibtool* stuff from old xcode/osx, but with new mac you might miss them, and need to hack with linking for example.

**Comment by andreacremaschi** [comment]
Well, the important part here is: you need to have automake/autoconf/libtool installed :)
Happy you solved
